### ISSUE TITLE
examples of all these required variables

### ISSUE THREAD

**Issue by rastarr** [ledgersmb/ledgersmb-docker#33]
Never used this before. Typically, I've found if I need to go into a compose file, that the authors could graciously suggest what the variables, that need to be edited, are located and what they refer to. It is no easy task for a newbie to wade in, unprepared and change stuff, without knowing what these changes refer to.

My first attempt with an unchanged compose file results in -

'WARN[0000] The "HOME_DEV" variable is not set. Defaulting to a blank string. 
invalid mount config for type "bind": field Source must not be empty'

I've got no idea what any of that means. Nor have I found any online tutorials that could help me.

Could anyone at least tell me the variables and lines in the compose file that I need to change and what I also need to set these variables to? At least this would get me started, I hope.

**Comment by ehuelsmann** [comment]
Hi Martin,

Thanks for contacting us with your issues. Your problem is relatively easily explained by the fact that you ended up using the developer's version of the docker compose project. The consumer version is https://github.com/ledgersmb/ledgersmb-docker/blob/1.10/docker-compose.yml and does not have these weird variables like $HOME_DEV. Even more: it has only 2 variables, which can be set through environment variables in the docker-compose environment:

```bash
LSMB_WORKERS=2 POSTGRES_PASSWORD=my-secret-password docker-compose up -d
```

To help prevent confusion for potential future users: where did you find the reference to this docker compose project? I'll need to add notes that there are non-developer compose projects that people much more likely want.

**Comment by ehuelsmann** [comment]
@rastarr did my comment above solve your problems? If so, would you please close the issue? If not, I'd love to help. Please describe any remaining issues you might have.

**Comment by rastarr** [comment]
actually no. I installed a preloaded VM instead. thanks anyway tho
